name: open_budget
description: "Open Budget is open-source, cross-platform budgeting application."
publish_to: 'none'
version: 0.2.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.3
  drift_dev: ^2.29.0

flutter:
  uses-material-design: true
